### ISSUE TITLE
Use setcap on the base OpenJDK images to allow ICMP requests

### ISSUE THREAD

**Issue by agalue** [opennms-forge/opennms-base-container#1]
When running OpenNMS or Minion as non-root, the current solution forces the user to set some kernel level flags to allow ICMP request to the opennms/minion user.

Unfortunately, these kernel flags require a fairly recent kernel, and common distributions like CentOS/RHEL won't support that flag, making the usage on OpenShift very difficult  (and in some cases Kubernetes or Docker) , as this imposes restriction on the operating system.

We found that using `setcap` on the `java` binary give us the possibility to run ICMP requests as non-root, similar to how the `ping` command works, so there is no need to specify kernel flags, making possible to run Minion and OpenNMS on any Linux distribution as the base OS as non-root.

Certainly, we can add the required changes to the `Dockerfile` of each individual app, but I believe it makes sense to have it available on the `base` image.

Here are the changes in question:

```bash
setcap cap_net_raw+ep ${JAVA_HOME}/bin/java && \
echo ${JAVA_HOME}/lib/jli > /etc/ld.so.conf.d/java-latest.conf && \
ldconfig
```

> **IMPORTANT**: This should be added at the last 3 commands, because the Java RPMs can be updated during the building process if there are newer packages. I found that this is a real possibility on my latest tests.

The above should work on OpenJDK 11, and the solution was tested recently with Horizon.

**Comment by agalue** [comment]
Something interesting to keep in mind.

The suggested changes work for OpenJDK 11, but won't work on OpenJDK 8, as the directory for `jli` is slightly different.

For OpenJDK 8 it should be `/usr/lib/jvm/java-1.8.0/lib/amd64/jli` or `${JAVA_HOME}/lib/amd64/jli`

**Comment by agalue** [comment]
During my tests, I found that the solution doesn't work with OpenJDK 8, but it does work with OpenJDK 11, so the upcoming releases like Horizon 24 and Meridian 2019 can benefit from it.

**Comment by indigo423** [comment]
I have added these in our base-horizon image here: https://github.com/opennms-forge/opennms-base-container/blob/31d7be499ccb75dc3d20f9d13d239abd481b472b/projects/base-horizon-jdk11/Dockerfile#L22

**Comment by indigo423** [comment]
I have added these in our base-horizon image here: https://github.com/opennms-forge/opennms-base-container/blob/31d7be499ccb75dc3d20f9d13d239abd481b472b/projects/base-horizon-jdk11/Dockerfile#L22
